export const pspResponse = [
  {
    create_time: "2020-10-12 15:22:57",
    update_time: "2020-10-12 15:22:57",
    provider_id: "3",
    provider_name: "MTN MOMO",
    provider_logo: "https://core.payunit.net/resources/flags/mtn.png",
    provider_short_tag: "mtnmomo",
    provider_status: "ACTIVE",
    delete_time: null,
    service_accounts_account_id: null,
    service_accounts_users_user_id: null,
    providers_provider_id: null,
  },
  {
    create_time: "2020-10-12 15:26:38",
    update_time: "2020-11-05 06:14:05",
    provider_id: "5",
    provider_name: "EXPRESS UNION MOBILE",
    provider_logo: "https://core.payunit.net/resources/flags/eu.png",
    provider_short_tag: "eu",
    provider_status: "ACTIVE",
    delete_time: null,
    service_accounts_account_id: null,
    service_accounts_users_user_id: null,
    providers_provider_id: null,
  },
  {
    create_time: "2020-12-01 15:55:50",
    update_time: "2020-12-01 16:33:53",
    provider_id: "22",
    provider_name: "ORANGE MONEY",
    provider_logo: "https://core.payunit.net/resources/flags/orange.png",
    provider_short_tag: "orange",
    provider_status: "ACTIVE",
    delete_time: null,
    service_accounts_account_id: null,
    service_accounts_users_user_id: null,
    providers_provider_id: null,
  },
  {
    create_time: "2021-01-07 16:00:05",
    update_time: "2021-01-07 16:00:05",
    provider_id: "23",
    provider_name: "VISA/MASTERCARD",
    provider_logo: "https://core.payunit.net/resources/flags/cb.png",
    provider_short_tag: "stripe",
    provider_status: "ACTIVE",
    delete_time: null,
    service_accounts_account_id: null,
    service_accounts_users_user_id: null,
    providers_provider_id: null,
  },
  {
    create_time: "2021-01-22 14:13:16",
    update_time: "2021-01-22 14:13:16",
    provider_id: "25",
    provider_name: "PAYPAL",
    provider_logo: "https://core.payunit.net/resources/flags/paypal.png",
    provider_short_tag: "paypal",
    provider_status: "ACTIVE",
    delete_time: null,
    service_accounts_account_id: null,
    service_accounts_users_user_id: null,
    providers_provider_id: null,
  },
];
